all: build/muon build/muoc

build: 
	mkdir build

build/muon: build muon/main.go
	GOARM=7 GOOS=linux GOARCH=arm go build -v -i -o build/muon muon/*.go

build/muoc: build muoc/main.go
	GOARM=7 GOOS=linux GOARCH=arm go build -v -i -o build/muoc muoc/*.go

clean:
	rm -r build
